# Generated by Django 3.0.2 on 2020-01-16 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('gen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=50, unique=True)),
                ('added_pokemons', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pokedex_desc', models.TextField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(max_length=150)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('generation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Generation')),
            ],
        ),
    ]
