# Generated by Django 3.0.2 on 2020-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spanish_name', models.CharField(max_length=50, unique=True)),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
