# Generated by Django 3.0.2 on 2020-01-17 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('move_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spanish_name', models.CharField(max_length=50, unique=True)),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Physical', 'Physical'), ('Special', 'Special')], max_length=10)),
                ('power', models.PositiveIntegerField()),
                ('accuracy', models.IntegerField(default=100, null=True)),
                ('secondary_effect', models.CharField(max_length=100)),
                ('min_power_points', models.PositiveIntegerField()),
                ('max_power_points', models.PositiveIntegerField()),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('contact', models.BooleanField()),
                ('magic_coat_affected', models.BooleanField()),
                ('snatch_affected', models.BooleanField()),
                ('protect_affected', models.BooleanField()),
                ('kings_rock_affected', models.BooleanField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Type')),
            ],
        ),
    ]
