# Generated by Django 3.0.2 on 2020-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Special', 'Special'), ('Status', 'Status')], max_length=10),
        ),
    ]
