# Generated by Django 3.0.2 on 2020-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200117_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
