# Generated by Django 3.0.2 on 2020-01-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200117_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='primary_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_type', to='main.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='secondary_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_type', to='main.Type'),
        ),
    ]
