# Generated by Django 3.0.2 on 2020-01-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200119_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='abilities', to='main.Ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_ability', to='main.Ability'),
        ),
    ]
