# Generated by Django 3.0.2 on 2020-01-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200119_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokedex_desc',
        ),
    ]
